apiVersion: v1
kind: Pod
metadata:
  name: pod6
  labels:
    app: myApp
spec:
  containers:
  - name: c1
    image: nginx
    ports:
    - containerPort: 80
      name: httpd-port
      protocol: TCP
