Vagrant.configure("2") do |config|
    config.vm.box = "generic/ubuntu2204"

    config.vm.define "manager" do |server|
      server.vm.network "public_network", type: "dhcp"
      server.vm.hostname = "manager"
      server.vm.provision "shell", path: "script.sh"
    end
  
    config.vm.define "worker" do |client|
      client.vm.network "public_network", type: "dhcp"
      client.vm.hostname = "worker"
      client.vm.provision "shell", path: "script.sh"
    end
  
    if Vagrant.has_plugin?("vagrant-vbguest")
      config.vbguest.auto_update = false
    end
  
end
